typography_spectrum: 0.4421739443205297
color:
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
  brandStrength: 0.3578524470794946
  lightness: 0.23844363912940025
  saturation: 0.06055554235354066
  rhythmicContrast: 0.725763394497335
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.32493417616933584
analytics:
  google: UA-79999338-1
  facebook: null
  twitter: null
author:
  name: Marcos Bernal-Salas
  email: marcos@marcoswrites.com
name: Marcos Writes
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Movie Trailers
    id: 46ac2c45-0e78-4291-b39d-6cbc2b974474
    type: content
  - name: 'Movie Trailer Tuesday: Resident Evilâ€™s Final Chapter'
    id: b20888c9-7234-4f80-b9bc-46890073890d
    type: content
favicon: null
title: Marcos Writes
description: Movie reviews (and news) in 500 words or less
purpose: []
